### ISSUE TITLE
clipshot mistakes Windows for Mac

### ISSUE THREAD

**Issue by vanbang9710** [ObserverOfTime/mpv-scripts#11]
### Script(s)

`clipshot.lua`

### Description

Line 32 is section for MacOS

### Steps to Reproduce

- Copy clipshot.lua to the scripts folder
- Play mpv
Error: [   0.085][f][clipshot] Lua error: ...op/apps/mpv/current/portable_config/scripts/clipshot.lua:32: attempt to concatenate a nil value

### Operating System(s)

- [X] Windows
- [ ] Linux
- [ ] macOS

### MPV version

0.35.1

### Lua version

can't find

**Comment by ObserverOfTime** [comment]
Fixed in 258fd63.
