### ISSUE TITLE
Add in https://nudin.github.io/mpv-script-directory/

### ISSUE THREAD

**Issue by z8512** [ObserverOfTime/mpv-scripts#9]
### Script(s)

`misc.lua`

### Description

Mplug is a script manager for mpv

### Operating System(s)

- [X] Windows
- [X] Linux
- [X] macOS

**Comment by z8512** [comment]
@ObserverOfTime

**Comment by ObserverOfTime** [comment]
Feel free to add whatever script you want there yourself.
